### ISSUE TITLE
@BOBBYWY comic advertisement

### ISSUE THREAD

**Issue by BOBBYWY** [amberisvibin/chibi-pc09#8]
Didn't know how else to contact you.  
Appreciate the 6809 project.

For downtime you might like Questionable Content comic on the net.  Latest one - https://www.questionablecontent.net/view.php?comic=4527

Based around a coffee shop in MA with a lot of quirky characters, including robots.

**Comment by amberisvibin** [comment]
> Didn't know how else to contact you.
> Appreciate the 6809 project.
> 
> For downtime you might like Questionable Content comic on the net. Latest one - https://www.questionablecontent.net/view.php?comic=4527
> 
> Based around a coffee shop in MA with a lot of quirky characters, including robots.

the issues page on my github is not the place to advertise.
i will add an email to my profile page.
please don't do this again.
